<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>jobshunter</artifactId>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <artifactId>annotation-processor</artifactId>
              <groupId>com.jobshunter</groupId>
              <version>${project.version}</version>
            </path>
          </annotationProcessorPaths>
          <release>${maven.compiler.release}</release>
        </configuration>
        <version>3.13.0</version>
      </plugin>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
        <groupId>org.springframework.boot</groupId>
        <version>${spring.boot.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>

      <plugin>
        <artifactId>frontend-maven-plugin</artifactId>
        <configuration>
          <workingDirectory>${project.parent.basedir}</workingDirectory>
        </configuration>
        <executions>
          <!-- 1. Install Node and npm -->
          <execution>
            <configuration>
              <nodeVersion>v20.11.1</nodeVersion>
            </configuration>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <id>install node and npm</id>
          </execution>

          <!-- 2. Run npm install -->
          <execution>
            <configuration>
              <arguments>install</arguments>
            </configuration>
            <goals>
              <goal>npm</goal>
            </goals>
            <id>npm install</id>
          </execution>

          <!-- 3. Run npm run build (Vite build) -->
          <execution>
            <configuration>
              <arguments>run build</arguments>
            </configuration>
            <goals>
              <goal>npm</goal>
            </goals>
            <id>npm run build</id>
          </execution>
        </executions>
        <groupId>com.github.eirslett</groupId>
        <version>1.15.0</version>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>false</filtering>
      </resource>
    </resources>
  </build>

  <dependencies>
    <dependency>
      <artifactId>annotation-processor</artifactId>
      <groupId>com.jobshunter</groupId>
      <scope>provided</scope>
      <version>${project.version}</version>
    </dependency>

    <!-- SPRING -->
    <dependency>
      <artifactId>spring-web</artifactId>
      <groupId>org.springframework</groupId>
      <version>${spring.web}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-embed-el</artifactId>
          <groupId>org.apache.tomcat.embed</groupId>
        </exclusion>
      </exclusions>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-security</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-mail</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-jdbc</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-validation</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-embed-el</artifactId>
          <groupId>org.apache.tomcat.embed</groupId>
        </exclusion>
      </exclusions>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-logging</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <groupId>org.springdoc</groupId>
      <version>2.6.0</version>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-webmvc-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
      <version>${spring.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>h2</artifactId>
      <groupId>com.h2database</groupId>
      <version>2.3.232</version>
    </dependency>
    <dependency>
      <artifactId>compiler</artifactId>
      <groupId>com.github.spullara.mustache.java</groupId>
      <version>0.9.14</version>
    </dependency>
    <dependency>
      <artifactId>httpclient5</artifactId>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <version>5.5.1</version>
    </dependency>
    <dependency>
      <artifactId>jakarta.el-api</artifactId>
      <groupId>jakarta.el</groupId>
      <version>5.0.0</version>
    </dependency>
    <dependency>
      <artifactId>expressly</artifactId>
      <groupId>org.glassfish.expressly</groupId>
      <version>5.0.0</version>
    </dependency>
    <dependency>
      <artifactId>jspecify</artifactId>
      <groupId>org.jspecify</groupId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <artifactId>liquibase-core</artifactId>
      <groupId>org.liquibase</groupId>
      <version>${liquibase.version}</version>
    </dependency>
    <dependency>
      <artifactId>mysql-connector-j</artifactId>
      <groupId>com.mysql</groupId>
      <version>${mysql.version}</version>
    </dependency>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
      <version>${lombok.version}</version>
    </dependency>
    <dependency>
      <artifactId>jakarta.servlet-api</artifactId>
      <groupId>jakarta.servlet</groupId>
      <version>6.1.0</version>
    </dependency>
    <dependency>
      <artifactId>jakarta.enterprise.cdi-api</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>jakarta.el-api</artifactId>
          <groupId>jakarta.el</groupId>
        </exclusion>
      </exclusions>
      <groupId>jakarta.enterprise</groupId>
      <version>4.0.1</version>
    </dependency>
    <dependency>
      <artifactId>jakarta.inject-api</artifactId>
      <groupId>jakarta.inject</groupId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <artifactId>jackson-databind</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
      <version>${joackson.databind}</version>
    </dependency>
    <dependency>
      <artifactId>jackson-dataformat-xml</artifactId>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <version>${joackson.databind}</version>
    </dependency>
    <dependency>
      <artifactId>jjwt-api</artifactId>
      <groupId>io.jsonwebtoken</groupId>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <artifactId>jjwt-impl</artifactId>
      <groupId>io.jsonwebtoken</groupId>
      <scope>runtime</scope>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <artifactId>bucket4j_jdk17-core</artifactId>
      <groupId>com.bucket4j</groupId>
      <version>8.15.0</version>
    </dependency>
    <dependency>
      <artifactId>jjwt-jackson</artifactId>
      <groupId>io.jsonwebtoken</groupId>
      <scope>runtime</scope>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <artifactId>slf4j-api</artifactId>
      <groupId>org.slf4j</groupId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>twilio</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>slf4j-api</artifactId>
          <groupId>org.slf4j</groupId>
        </exclusion>
      </exclusions>
      <groupId>com.twilio.sdk</groupId>
      <version>11.0.3</version>
    </dependency>
    <dependency>
      <artifactId>resilience4j-spring-boot3</artifactId>
      <groupId>io.github.resilience4j</groupId>
      <version>${resilience4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>resilience4j-ratelimiter</artifactId>
      <groupId>io.github.resilience4j</groupId>
      <version>${resilience4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>resilience4j-circuitbreaker</artifactId>
      <groupId>io.github.resilience4j</groupId>
      <version>${resilience4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>resilience4j-bulkhead</artifactId>
      <groupId>io.github.resilience4j</groupId>
      <version>${resilience4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>resilience4j-timelimiter</artifactId>
      <groupId>io.github.resilience4j</groupId>
      <version>${resilience4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>jsoup</artifactId>
      <groupId>org.jsoup</groupId>
      <version>1.21.2</version>
    </dependency>

    <!-- TEST -->
    <dependency>
      <artifactId>wiremock-jre8-standalone</artifactId>
      <groupId>com.github.tomakehurst</groupId>
      <scope>test</scope>
      <version>2.35.2</version>
    </dependency>
    <dependency>
      <artifactId>javax.servlet-api</artifactId>
      <groupId>javax.servlet</groupId>
      <scope>test</scope>
      <version>4.0.1</version>
    </dependency>
  </dependencies>
  <description>Daily automated job hunter based on your CV</description>
  <modelVersion>4.0.0</modelVersion>
  <name>application</name>

  <packaging>jar</packaging>

  <parent>
    <artifactId>jobshunter-parent</artifactId>
    <groupId>com.jobshunter</groupId>
    <version>1.0.0</version>
  </parent>

  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <url>https://repo1.maven.org/maven2/</url>
    </pluginRepository>
  </pluginRepositories>

  <profiles>
    <profile>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <id>local</id>
      <properties>
        <spring-boot.run.profiles>local</spring-boot.run.profiles>
        <spring.profiles.active>local</spring.profiles.active>
      </properties>
    </profile>
    <profile>
      <id>test</id>
      <properties>
        <spring-boot.run.profiles>test</spring-boot.run.profiles>
        <spring.profiles.active>test</spring.profiles.active>
      </properties>
    </profile>
    <profile>
      <id>prod</id>
      <properties>
        <spring-boot.run.profiles>prod</spring-boot.run.profiles>
        <spring.profiles.active>prod</spring.profiles.active>
      </properties>
    </profile>
  </profiles>

  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo1.maven.org/maven2/</url>
    </repository>
  </repositories>
</project>

