services:
#  mysql:
#    image: mysql:8.4
#    restart: always
#    container_name: scm-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: jobshunter_db
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#volumes:
#  mysql_data:

  jobshunter-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: JobsHunterContainer
    restart: always
    networks:
      - jobshunter-net
#    depends_on:
#      mysql:
#        condition: service_healthy
    environment:
#      MYSQL_URL: mysql://mysql:3306/jobshunter_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      #Connection to database from local machine
      MYSQL_URL: mysql://host.docker.internal:3306/jobshunter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      MAILTRAP_API_KEY: ${MAILTRAP_API_KEY}
      MAILTRAP_TEMPLATE_NEWJOBS: ${MAILTRAP_TEMPLATE_NEWJOBS}
      MAIL_FROM: ${MAIL_FROM}
      SERP_API_KEY: ${SERP_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      PROFILE: prod
      SPRING_PROFILES_ACTIVE: prod
      LIQUIBASE_ENABLED: "true"
      SERVER_PORT: 9001
    ports:
      - "9001:9001"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: start --all --config /ngrok/ngrok.yml
    ports:
      - "4040:4040"
    volumes:
      - D:\ngrok.yml:/ngrok/ngrok.yml
    networks:
      - jobshunter-net
    depends_on:
      - jobshunter-service

networks:
  jobshunter-net:
    driver: bridge
