services:

  jobshunter-service:
    profiles:
      - local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "https://ronin-archesporial-lonnie.ngrok-free.dev/"
    container_name: JobsHunterContainer
    restart: always
    networks:
      - jobshunter-net
    volumes:
      - playwright-cache:/root/.cache/ms-playwright
    #    depends_on:
#      mysql:
#        condition: service_healthy
    environment:
#      MYSQL_URL: mysql://mysql:3306/jobshunter_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      #Connection to database from local machine
      MYSQL_URL: mysql://host.docker.internal:3306/jobshunter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true&createDatabaseIfNotExist=true
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      GROK_API_KEY: ${GROK_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      MAILTRAP_API_KEY: ${MAILTRAP_API_KEY}
      MAILTRAP_TEMPLATE_NEWJOBS: ${MAILTRAP_TEMPLATE_NEWJOBS}
      IPINFO_API_KEY: ${IPINFO_API_KEY}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SSL_PORT: 8443
      MAIL_FROM: ${MAIL_FROM}
      SERP_API_KEY: ${SERP_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      PROFILE: prod
      SPRING_PROFILES_ACTIVE: prod
      LIQUIBASE_ENABLED: "true"
      ENABLE_SCHEDULER: "false"
    ports:
      - "9001:8443"
  mysql-service-aws:
    profiles:
      - aws
    image: mysql:8.4
    restart: always
    container_name: jobshunter-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: jobshunter
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  jobshunter-service-aws:
    profiles:
      - aws
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "https://ec2-16-171-239-161.eu-north-1.compute.amazonaws.com"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
    container_name: JobsHunterContainer
    restart: always
    volumes:
      - playwright-cache:/root/.cache/ms-playwright
    depends_on:
      mysql-service-aws:
        condition: service_healthy
    environment:
      MYSQL_URL: mysql://mysql-service-aws:3306/jobshunter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true&createDatabaseIfNotExist=true
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      GROK_API_KEY: ${GROK_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      MAILTRAP_API_KEY: ${MAILTRAP_API_KEY}
      MAILTRAP_TEMPLATE_NEWJOBS: ${MAILTRAP_TEMPLATE_NEWJOBS}
      IPINFO_API_KEY: ${IPINFO_API_KEY}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SSL_PORT: 8443
      MAIL_FROM: ${MAIL_FROM}
      SERP_API_KEY: ${SERP_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      PROFILE: prod
      SPRING_PROFILES_ACTIVE: prod
      LIQUIBASE_ENABLED: "true"
      ENABLE_SCHEDULER: "false"
    ports:
      - "443:8443"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    command: start --all --config /ngrok/ngrok.yml
    ports:
      - "4040:4040"
    volumes:
      - D:\ngrok.yml:/ngrok/ngrok.yml
    networks:
      - jobshunter-net
    depends_on:
      - jobshunter-service
    profiles:
      - local

networks:
  jobshunter-net:
    driver: bridge

volumes:
  mysql_data:
  playwright-cache: