spring:
  config:
    activate:
      on-profile: local
  mail:
    enabled: false

jobshunter:
  scheduler:
    processOrderFrequency: 2000
    notifyUsersFrequency: 3000
    cleanupFiles: 86400000

twilio:
  enabled: false

gemini:
  enabled: false

ipinfo:
  enabled: false

gpt:
  enabled: false

grok:
  enabled: false

serp:
  enabled: false
  maxPageSearch: 1

security:
  jwt:
    secret: ${JWT_SECRET:change-me-dev-secret-please-keep-long}
    expiration-sec: 86400 # 24h
  refresh-token:
    pepper: ${REFRESH_TOKEN_PEPPER:VXjjT1rcofkUX9JpdHrdlA==} # generate using openssl rand -base64 48
    expiration-sec: 2592000 # 30 days
  cookie:
    device-id:
      expiration-sec: 2592000 # 30 days
  httpsOnly:
    enabled: false

# RATE LIMITER  ---------------------------------------------------------------------------
# Throttle API requests to 2 per minute, preventing quota violations and automatic request queueing
# with transparent permit management.

resilience4j.ratelimiter:
  instances:
    gptLimiter:
      limitForPeriod: 1                # Allow 1 call
      limitRefreshPeriod: 5s           # Every 1 seconds
      timeoutDuration: 10s             # Wait up to 10s for a slot
      writableStackTraceEnabled: false
    grokLimiter:
      limitForPeriod: 1                # Allow 1 call
      limitRefreshPeriod: 5s           # Every 1 seconds
      timeoutDuration: 10s             # Wait up to 10s for a slot
      writableStackTraceEnabled: false
    geminiLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 10s
      writableStackTraceEnabled: false
    serpLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 5s
      timeoutDuration: 10s
      writableStackTraceEnabled: false
    twilioLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 5s
      timeoutDuration: 10s
      writableStackTraceEnabled: false
    tinyurlLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 5s
      timeoutDuration: 10s
      writableStackTraceEnabled: false
    mailtrapLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 5s
      timeoutDuration: 10s
      writableStackTraceEnabled: false

# CIRCUIT BREAKER ---------------------------------------------------------------------------
# Fault tolerance by monitoring API call failures.
# Automatically opens the circuit to prevent cascading failures when error threshold is exceeded,
# failing fast and allowing services to recover before retrying requests.

#registerHealthIndicator: expose a health indicator for this circuit breaker via actuator.
#slidingWindowType: use a COUNT_BASED window (by number of calls) for metrics.
#slidingWindowSize: track the last slidingWindowSize calls in the sliding window.
#minimumNumberOfCalls: start calculating failure stats only after at least minimumNumberOfCalls calls.
#failureRateThreshold: open the breaker if the failure rate exceeds failureRateThreshold %.
#slowCallRateThreshold: treat slow calls as a problem when more than slowCallRateThreshold % are slow.
#slowCallDurationThreshold: any call slower than slowCallDurationThreshold sec is counted as “slow.”
#waitDurationInOpenState: keep the breaker open for waitDurationInOpenState sec before trying again (half-open).
#permittedNumberOfCallsInHalfOpenState: allow that number of trial calls while half-open.
resilience4j.circuitbreaker:
  instances:
    gptCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    grokCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    geminiCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    serp:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    twilio:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    mailtrap:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    tinyurl:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5s
      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1

# BULK HEAD  ---------------------------------------------------------------------------
# Isolates thread pools to limit concurrent requests to external services,
# preventing resource exhaustion and ensuring one failing service doesn't impact others.

resilience4j.bulkhead:
  instances:
    gptBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    grokBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    geminiBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    serpBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    mailtrapBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    twilioBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false