server:
  port: ${SSL_PORT:8443}
  forward-headers-strategy: FRAMEWORK
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE:classpath:jobshunter.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:jobshunter}
    enabled-protocols: TLSv1.3,TLSv1.2
    ciphers: >
      TLS_AES_256_GCM_SHA384,
      TLS_AES_128_GCM_SHA256
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  http2:
    enabled: true

jobshunter:
  name: JobsHunter
  expiredExpressions: was expired,is expired,no longer exists,This job was available,is no longer active,job is no longer available,this job was removed,Job not found,Applications from candidates outside of our global target markets are currently not accepted,No longer accepting applications,The job ad is no longer active,Application not possible,This job opening is no longer available,The vacancy has expired,this position has been filled,ONLY on W2,The job you are looking for is no longer open,Oferta no disponible,This job posting is no longer available,this job has expired,this position has been filled,This job offer is not active,Applications are closed,This job offer is not available,This position is no longer open,This page could not be found,The job you were looking for was not found,We can’t find this page,Job is OOO,This job offer is no longer valid,Poziția nu are o recrutare activă,Page Not Found,This position has just been filled
  blacklist: dailyremote.com,remote.co,wellfound.com,weworkremotely.com,upwork.com
  blacklistJobsCompanySearch: linkedin.com,bestjobs.eu,ejobs.ro,hipo.ro,indeed.com,glassdoor.com,monster.com,ziprecruiter.com,careerbuilder.com,simplyhired.com,adzuna.com,jooble.org,jobrapido.com,jobsora.com,joblift.com,jobisjob.com,neuvoo.com,talent.com,remotive.com,remoteok.com,dailyremote.com,remote.co,weworkremotely.com,wellfound.com,angel.co,flexjobs.com,justremote.co,workingnomads.com,powertofly.com,remotewoman.com,remotejobs.com,euremotejobs.com,eu-remote.jobs,stackoverflow.com,dice.com,hired.com,technojobs.co.uk,totaljobs.com,reed.co.uk,cv-library.co.uk,jobsdb.com,seek.com,jobstreet.com,glassdoor.ie,xing.com,stepstone.com,arbeitsagentur.de,no-fluff-jobs.com,bulldogjob.com,landing.jobs,itjobs.pt,jobs.ie,irishjobs.ie,reedglobal.com,jobserve.com,freelancer.com,upwork.com,toptal.com,peopleperhour.com,guru.com,scale.jobs,theladders.com,collegerecruiter.com,wearedevelopers.com,roberthalf.com,otta.com,builtin.com,levels.fyi,craigslist.org,usajobs.gov,naukri.com,bayt.com,careerjet.com,snagajob.com,themuse.com,idealist.org,handshake.com,mediabistro.com,dribbble.com,behance.net,fiverr.com,99designs.com,51job.com,zhaopin.com,jobs.cz,pracuj.pl,hh.ru,rabota.ua,gulftalent.com,timesjobs.com,shine.com,jobberman.com,careers24.com,pnet.co.za,authenticjobs.com,coroflot.com,krop.com,ventureloop.com,eures.europa.eu,europelanguagejobs.com,eurojobs.com,jobsinnetwork.com,workcircle.com,europeanjobdays.eu,welcometothejungle.com,jobandtalent.com,tyba.com,jobfluent.com,graduateland.com,learn4good.com,meteojob.com,pole-emploi.fr,jobs.ch,karriere.at,vdab.be,jobindex.dk,infojobs.net,infoempleo.com,arbetsformedlingen.se,finn.no,netempregos.pt,domestika.org,xpatjobs.com,make-it-in-germany.com,jobgether.com,jobs.euractiv.com
  localJobExpressions: onsite,on-site,on site,hybrid,office based,office-based,in office,in-office,la sediu,lucru la birou,prezenta la birou,prezenta fizica,program hibrid,model hibrid,lucru de la birou,la biroul companiei,activitate la sediu,prezenta obligatorie,lucru onsite,This position requires local presence
  freelancerExpressions: b2b,contractor,colaborator,independent contractor,freelance,freelancer,self employed,self-employed,1099,corp to corp,c2c,contract basis,contract role,contract position,consultant,external consultant,pe baza de contract,contract de colaborare,colaborare,pfa,srl,persoana juridica,facturare,plata pe factura,prestari servicii,contract de prestari servicii,consultanta
  remoteExpressions: remote,fullyremote,remoteonly,100%remote,100percentremote,workfromhome,wfh,homeoffice,distributedteam,distributedwork,anywhere,workfromanywhere,locationindependent,locationagnostic,remote-first,remotefirst,remoteenvironment,virtualrole,lucru remote,lucru de acasa,full remote,remote complet,complet remote,oriunde,lucru de oriunde,distribuit,echipa distribuita,fara prezenta la birou
  threads:
    urlFetchRestClient: 30
    urlFetchPlaywright: 1
    jobProcessing : 10
    orders: 3
    notifications: 1
    async: 3
    maintenance: 1
  scheduler:
    enabled: ${ENABLE_SCHEDULER:true}
    processOrderFrequency: 5000
    notifyUsersFrequency: 60000
    cleanupFiles: 86400000
  additionalEffort:
    maxRetries: 3
  ratelimit:
    capacity: 60
    window: 1m

twilio:
  enabled: true
  account-sid: ${TWILIO_ACCOUNT_SID:notset}
  auth-token: ${TWILIO_AUTH_TOKEN:notset}
  from-number: ${TWILIO_WHATSAPP_FROM:notset}

gemini:
  enabled: true
  apiKey: ${GEMINI_API_KEY:notset}
  threads: 10

gpt:
  enabled: true
  apiKey: ${CHATGPT_API_KEY:notset}
  threads: 20

grok:
  enabled: true
  apiKey: ${GROK_API_KEY:notset}
  threads: 10

serp:
  enabled: true
  apiKey: ${SERP_API_KEY:notset}
  threads: 10
  maxPageSearch: 5

ipinfo:
  enabled: true
  apiKey: ${IPINFO_API_KEY:notset}
  threads: 1

spring:
  profiles:
    default: ${PROFILE:local}
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:${MYSQL_URL:mysql://localhost:3306/jobshunter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true&createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:notset}
    password: ${MYSQL_PASSWORD:notset}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate.validator.message_interpolator: org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.xml
  main:
    banner-mode: off
    lazy-initialization: true
  mail:
    enabled: true
    host: send.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME:notset}
    password: ${MAILTRAP_PASSWORD:notset}
    from: ${MAIL_FROM:no-reply@mailtrap.io}
    apiKey: ${MAILTRAP_API_KEY:notset}
    templateUUID: ${MAILTRAP_TEMPLATE_NEWJOBS:notset}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.from: ${MAIL_FROM:no-reply@mailtrap.io}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:notset}
            client-secret: ${GOOGLE_CLIENT_SECRET:notset}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
    jwt:
      secret: ${JWT_SECRET:change-me-dev-secret-please-keep-long}
      expiration-sec: 3600 # 1h
    refresh-token:
      pepper: ${REFRESH_TOKEN_PEPPER:change-me-dev-secret-please-keep-long} # generate using openssl rand -base64 48
      expiration-sec: 2592000 # 30 days
    cookie:
      device-id:
        expiration-sec: 2592000 # 30 days
    cors:
      allowed-origins:
        - "https://ronin-archesporial-lonnie.ngrok-free.dev"
    httpsOnly:
      enabled: true

logging:
  level:
    root: INFO
    com.jobshunter: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    # Core Resilience4j
    io.github.resilience4j.retry: WARN
    io.github.resilience4j.circuitbreaker: WARN
    io.github.resilience4j.bulkhead: WARN
    io.github.resilience4j.ratelimiter: WARN
    # AOP Aspects (FOARTE IMPORTANT)
    io.github.resilience4j.retry.internal: WARN
    io.github.resilience4j.circuitbreaker.internal: WARN
    io.github.resilience4j.bulkhead.internal: WARN
    io.github.resilience4j.ratelimiter.internal: WARN
    # Spring AOP proxying
    org.springframework.aop: WARN
    org.springframework.aop.framework: WARN

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yml
    disable-swagger-default-url: true

# ACTUATOR & METRICS ---------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: jobshunter
    distribution:
      percentiles-histogram:
        ai.api: true
        job.hunt: true
      percentiles:
        ai.api: 0.5, 0.95, 0.99
        job.hunt: 0.5, 0.95, 0.99

# RATE LIMITER  ---------------------------------------------------------------------------
# Throttle API requests to 2 per minute, preventing quota violations and automatic request queueing
# with transparent permit management.
# limitForPeriod: 1                # Allow 1 call
# limitRefreshPeriod: 30s           # Every 30 seconds
# timeoutDuration: 5m              # Wait up to 5min for a slot

resilience4j.ratelimiter:
  instances:
    gptLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 15m
      writableStackTraceEnabled: false
    grokLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 15m
      writableStackTraceEnabled: false
    geminiLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 15m
      writableStackTraceEnabled: false
    serpLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 20s
      timeoutDuration: 1m
      writableStackTraceEnabled: false
    twilioLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1m
      timeoutDuration: 30s
      writableStackTraceEnabled: false
    tinyurlLimiter:
      limitForPeriod: 5
      limitRefreshPeriod: 1m
      timeoutDuration: 30s
      writableStackTraceEnabled: false
    mailtrapLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1m
      timeoutDuration: 30s
      writableStackTraceEnabled: false
    ipinfoLimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 30s
      writableStackTraceEnabled: false

# CIRCUIT BREAKER ---------------------------------------------------------------------------
# Fault tolerance by monitoring API call failures.
# Automatically opens the circuit to prevent cascading failures when error threshold is exceeded,
# failing fast and allowing services to recover before retrying requests.

#registerHealthIndicator: expose a health indicator for this circuit breaker via actuator.
#slidingWindowType: use a COUNT_BASED window (by number of calls) for metrics.
#slidingWindowSize: track the last X calls in the sliding window.
#minimumNumberOfCalls: start calculating failure stats only after at least X calls.
#failureRateThreshold: open the breaker if the failure rate exceeds X %.
#slowCallRateThreshold: treat slow calls as a problem when more than X % are slow.
#slowCallDurationThreshold: any call slower than X sec is counted as “slow.”
#waitDurationInOpenState: keep the breaker open for X sec before trying again (half-open).
#permittedNumberOfCallsInHalfOpenState: allow that number of trial calls while half-open.
resilience4j.circuitbreaker:
  instances:
    gptCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    grokCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    geminiCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    serp:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    twilio:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    mailtrap:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    tinyurl:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2m

      waitDurationInOpenState: 2m
      permittedNumberOfCallsInHalfOpenState: 1
    ipinfo:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      slidingWindowSize: 3

      failureRateThreshold: 100
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 10s

      waitDurationInOpenState: 1m
      permittedNumberOfCallsInHalfOpenState: 1

# BULK HEAD  ---------------------------------------------------------------------------
# Purpose: Limit CONCURRENT requests
# Isolates thread pools to limit concurrent requests to external services,
# preventing resource exhaustion and ensuring one failing service doesn't impact others.
#  maxConcurrentCalls: 3              # 3 concurrent GPT calls
#  maxThreadPoolSize: 5               # Pool of 5 threads
#  coreThreadPoolSize: 1              # Keep 1 warm
#  queueCapacity: 20                  # Max 20 waiting
#  maxWaitDuration: 20m               # Wait max 20 minutes
#  keepAliveDuration: 30s             # Cleanup idle threads after 30s

resilience4j.bulkhead:
  instances:
    gptBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    grokBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    geminiBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    serpBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    mailtrapBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
    twilioBulkhead:
      bulkheadType: THREADPOOL
      maxConcurrentCalls: 3
      maxThreadPoolSize: 5
      coreThreadPoolSize: 1
      queueCapacity: 20
      maxWaitDuration: 20m
      keepAliveDuration: 30s
      writableStackTraceEnabled: false
