spring:
  config:
    activate:
      on-profile: local
  mail:
    enabled: false

twilio:
  enabled: false

gemini:
  enabled: false

gpt:
  enabled: false

serpApi:
  enabled: false
  apiKey: ${SERP_API_KEY:notset}
  maxPageSearch: 1
