server:
  port: 8081

jobshunter:
  prompt: "Search for job postings and return only URLs that satisfy all rules: 1) The job description must contain the keyword 'Java'. 2) The job description must contain at least two of the following keywords: contractor, B2B, remote, no travel, spring boot, rest api, postgresql, mysql, gcp, swt, rcp, microservices. 3) Consider only jobs posted in the last 24 hours. 4) Exclude pages that contain any of the following substrings (case-insensitive): 'job expired', 'hybrid', 'full-stack', 'fullstack'. 5) Exclude results from these hosts: linkedin.com, weworkremotely.com, dailyremote.com. 6) Allow a maximum of 3 URLs per host/domain. 7) Do not return URLs that give an HTTP status code in the range 400-599. 8) Sort all valid results in descending order by publication date. 9). Output should contains only URL's separated by empty space . No explanations. No extra text. Use my attached CV to match with job descriptions."
  cv-path: "cristian-tone-java-dev.pdf"
  scheduler:
    cron: "0 0 9 * * *"
  whatsapp:
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    from-number: ${TWILIO_WHATSAPP_FROM:}
    to-number: ${TWILIO_WHATSAPP_TO:}

logging:
  level:
    root: INFO
    com.jobshunter: DEBUG
