package com.jobshunter.model;

public enum PromptType {

  SYSTEM_PROMPT_MATCH_SCORE,
  SYSTEM_PROMPT_JOB_SEARCH,
  SYSTEM_PROMPT_COMPANY_SEARCH,

  USER_PROMPT_COMPANIES,
  USER_PROMPT_JOB,
  USER_PROMPT_MATCH_SCORE,

}
