package com.jobshunter.model;

public enum PromptType {

  SYSTEM_INSTRUCTIONS,

  SYSTEM_PROMPT_MATCH_SCORE,
  SYSTEM_PROMPT_JOB_SEARCH,
  SYSTEM_PROMPT_COMPANY_SEARCH,
  SYSTEM_PROMPT_JOBS_BY_COMPANY,

  USER_PROMPT_COMPANIES,
  USER_PROMPT_JOB,
  USER_PROMPT_JOB_BLACKLISTED,
  USER_PROMPT_MATCH_SCORE,

  DEVELOPER_PROMPT,

  USER_PROMPT_JOB_BLAME_1,

  USER_PROMPT_JOB_SERIES_1,
  USER_PROMPT_JOB_SERIES_2,
  USER_PROMPT_JOB_SERIES_3

}
